<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/Map_Stub_ModifySub_Resp.map" md5sum="03b9e75a5968ce53fdd214bb28f995d0" version="8.0.400" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		Map_Stub_ModifySub_Resp.map
*   Map declaration(s):	Map_Stub_ModifySub_Resp
*   Input file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FAS_SubmitResourceOrder_TIBCO%257DTibco_SharedBO/message%3D%257Bhttp%253A%252F%252FTPRMOAI%252FAIS%252FSubmitResourceOrder%257DinvokeMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/sharedContext%3D%257Bhttp%253A%252F%252FAS_SubmitResourceOrder_TIBCO%257DTibco_SharedBO/message%3D%257Bhttp%253A%252F%252FTPRMOAI%252FAIS%252FSubmitResourceOrder%257DinvokeResponseMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xltxe="http://www.ibm.com/xmlns/prod/xltxe-j"
    xmlns:math="http://exslt.org/math"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io3="http://www.ibm.com/telecom/v8.5.0/businessobject/system/sid-v12.5/systemview"
    xmlns:io2="http://www.ibm.com/telecom/v8.5.0/businessobject/system/sid-v12.5/common/extensions"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io18="http://www.ibm.com/telecom/v8.5.0/businessobject/system/sid-v12.5/fulfillment/extensions"
    xmlns:io17="http://www.ibm.com/software/issw/telecom/pack/v8.5.0/lite/businessobject/system/sid-v12.5"
    xmlns:io19="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io14="http://www.ibm.com/software/issw/telecom/pack/v8.5.0/lite/businessobject/system/common/extension"
    xmlns:io13="http://www.ibm.com/software/issw/telecom/pack/v8.5.0/lite/businessobject/system/fulfillment/extension"
    xmlns:io16="http://TIBCO_OSS_Library"
    xmlns:io15="http://www.ibm.com/software/issw/telecom/pack/v8.5.0/lite/businessobject/system/assurance/extension"
    xmlns:io23="http://www.ibm.com/telecom/v8.5.0/businessobject/system/sid-v12.5/billing/extensions"
    xmlns:io8="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io10="http://www.w3.org/2005/08/addressing"
    xmlns:io22="wsdl.http://TPRMOAI/AIS/SubmitResourceOrder"
    xmlns:io9="http://TPCMN"
    xmlns:io21="http://TPRMOAI/AIS/SubmitResourceOrder"
    xmlns:io6="http://www.ibm.com/telecom/v8.5.0/businessobject/system/sid-v12.5/common"
    xmlns:io12="http://www.ibm.com/telecom/v8.5.0/businessobject/system/sid-v12.5/messageview"
    xmlns:io20="http://www.ibm.com/telecom/v8.5.0/businessobject/system/sid-v12.5/assurance/extensions"
    xmlns:io7="http://www.ibm.com/software/issw/telecom/pack/v8.5.0/lite/businessobject/system/billing/extension"
    xmlns:io11="http://AS_SubmitResourceOrder_TIBCO"
    xmlns:map="http://AppS_SubmitResourceOrder_TIBCO/xslt/Map_Stub_ModifySub_Resp"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="math str set xs date fn exsl map xltxe msl"
    version="2.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io5:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:Map_Stub_ModifySub_Resp2">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io5:smo" mode="map:Map_Stub_ModifySub_Resp"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template match="io5:smo"  mode="map:Map_Stub_ModifySub_Resp">
    <io5:smo>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io22:invokeResponseMsg'"/>
        </xsl:attribute>
        <io21:invokeResponse>
          <submitResourceOrderOutput>
            <io12:Header>
              <!-- a simple data mapping: "context/shared/TransID"(string) to "io6:CorrelationId_T"(string) -->
              <xsl:if test="context/shared/TransID">
                <xsl:element name="io6:CorrelationId_T">
                  <xsl:value-of select="context/shared/TransID"/>
                </xsl:element>
              </xsl:if>
              <!-- a simple mapping with no associated source:  to "io6:ActivityStatusEnum_T"(string) -->
              <xsl:element name="io6:ActivityStatusEnum_T">
                <xsl:text>SUCCESS</xsl:text>
              </xsl:element>
              <!-- a simple mapping with no associated source:  to "io6:ActivityStatus_T"(string) -->
              <xsl:element name="io6:ActivityStatus_T">
                <xsl:text>200</xsl:text>
              </xsl:element>
            </io12:Header>
          </submitResourceOrderOutput>
        </io21:invokeResponse>
      </body>
    </io5:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template name="map:Map_Stub_ModifySub_Resp2">
    <xsl:param name="smo"/>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'io22:invokeResponseMsg'"/>
      </xsl:attribute>
      <io21:invokeResponse>
        <submitResourceOrderOutput>
          <io12:Header>
            <!-- a simple data mapping: "$smo/context/shared/TransID"(string) to "io6:CorrelationId_T"(string) -->
            <xsl:if test="$smo/context/shared/TransID">
              <xsl:element name="io6:CorrelationId_T">
                <xsl:value-of select="$smo/context/shared/TransID"/>
              </xsl:element>
            </xsl:if>
            <!-- a simple mapping with no associated source:  to "io6:ActivityStatusEnum_T"(string) -->
            <xsl:element name="io6:ActivityStatusEnum_T">
              <xsl:text>SUCCESS</xsl:text>
            </xsl:element>
            <!-- a simple mapping with no associated source:  to "io6:ActivityStatus_T"(string) -->
            <xsl:element name="io6:ActivityStatus_T">
              <xsl:text>200</xsl:text>
            </xsl:element>
          </io12:Header>
        </submitResourceOrderOutput>
      </io21:invokeResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::node()[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
