<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="ResourceOrderManagmentExport_WS_GetMessageFromQHttp_Service" targetNamespace="http://SterlingLib/GetMessageFromQ" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://SterlingLib/GetMessageFromQ">
  <wsdl:import location="GetMessageFromQ.wsdl" namespace="http://SterlingLib/GetMessageFromQ"/>
  <wsdl:binding name="ResourceOrderManagmentExport_WS_GetMessageFromQHttpBinding" type="this:GetMessageFromQ">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getMessage">
      <soap:operation soapAction=""/>
      <wsdl:input name="getMessageRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ResourceOrderManagmentExport_WS_GetMessageFromQHttpService">
    <wsdl:port binding="this:ResourceOrderManagmentExport_WS_GetMessageFromQHttpBinding" name="ResourceOrderManagmentExport_WS_GetMessageFromQHttpPort">
      <soap:address location="http://localhost:9080/AppS_SubmitResourceOrder_OMWeb/sca/ResourceOrderManagmentExport_WS"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>